---
apiVersion: v1
kind: Namespace
metadata:
  name: kayd
---
apiVersion: v1
kind: Pod
metadata:
  name: resources-pod-1
  namespace: kayd
spec:
  containers:
  - name: default-cpu
    image: nginx
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
      requests:
        cpu: "0.5"
        memory: "100Mi"