
---
apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-with-pod-001
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: name
            operator: In
            values:
            - anything
  containers:
  - name: node-affinity-with-pod-001
    image: nginx