---
apiVersion: v1
kind: Pod
metadata:
  name: pod-selector-001
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    name: anything