# With Secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret-1
data:
  DB_HOST: bXlzcWwK
  DB_USER: cm9vdAo=
  DB_PASSWORD: cm9vdAo=
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: myapp-pod-7
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: user
          valueFrom:
            secretKeyRef:
              name: app-secret-1
              key: DB_USER      
    