# With Secret
# env vars with volumes
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret-3
data:
  DB_HOST: bXlzcWwK
  DB_USER: cm9vdAo=
  DB_PASSWORD: cm9vdAo=
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: myapp-pod-9
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: my-volume
          mountPath: /etc/kayd
  volumes:
    - name: my-volume
      secret:
        secretName: app-secret-3
    