# With Secret
# envFrom
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret-2
data:
  DB_HOST: bXlzcWwK
  DB_USER: cm9vdAo=
  DB_PASSWORD: cm9vdAo=
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: myapp-pod-8
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
        - secretRef:
            name: app-secret-2
    