# With ConfigMap
# env vars with volumes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-3
data:
  APP_COLOR: blue3
  APP_MODE: prod3
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: myapp-pod-6
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: my-volume
          mountPath: /etc/kayd
  volumes:
    - name: my-volume
      configMap:
        name: app-config-3
    