# Security Context - Container Level
# run As User
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-11
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      securityContext:
        runAsUser: 1000

    