# With Entrypoint and CMD
# docker run --entrypoint="sleep" nginx 10
# docker run nginx sleep 10
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: myapp-pod-3
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      command:
        - "sleep"
      args:
        - "10"
    