---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: named-port
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - name: liveness-port
      containerPort: 80
      hostPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: liveness-port
    readinessProbe:
      httpGet:
        path: /
        port: liveness-port
    startupProbe:
      httpGet:
        path: /
        port: liveness-port
      failureThreshold: 30
      periodSeconds: 10