---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-pod-002
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 5
